version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env.development
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
