
-- Test Database Setup Script
-- This script sets up a test database with sample data

-- Create test database if it doesn't exist
CREATE DATABASE test_clinic_db;

-- Connect to test database
\c test_clinic_db;

-- Create test user
CREATE USER test_user WITH PASSWORD 'test_password';
GRANT ALL PRIVILEGES ON DATABASE test_clinic_db TO test_user;

-- Create test tables (this would be generated by Prisma)
-- The actual table creation will be handled by Prisma migrations

-- Insert test data
INSERT INTO "User" (id, username, email, password, role, status, created_at, updated_at) VALUES
('test-user-1', 'testuser', 'test@example.com', '$2b$10$hashedpassword', 'staff', 'active', NOW(), NOW()),
('test-admin-1', 'testadmin', 'admin@example.com', '$2b$10$hashedpassword', 'admin', 'active', NOW(), NOW()),
('test-doctor-1', 'testdoctor', 'doctor@example.com', '$2b$10$hashedpassword', 'doctor', 'active', NOW(), NOW()),
('test-pharmacist-1', 'testpharmacist', 'pharmacist@example.com', '$2b$10$hashedpassword', 'pharmacist', 'active', NOW(), NOW());

INSERT INTO "Patient" (id, first_name, last_name, national_id, phone, email, date_of_birth, gender, created_at, updated_at) VALUES
('test-patient-1', 'TestPatient', 'TestLastName', '1234567890123', '0812345678', 'testpatient@example.com', '1990-01-01', 'male', NOW(), NOW()),
('test-patient-2', 'TestPatient2', 'TestLastName2', '2345678901234', '0823456789', 'testpatient2@example.com', '1985-05-15', 'female', NOW(), NOW());

INSERT INTO "Product" (id, product_name, product_type, sale_price, unit, stock_quantity, sku, created_at, updated_at) VALUES
('test-product-1', 'Paracetamol 500mg', 'medication', 25, 'tablet', 100, 'PARA500', NOW(), NOW()),
('test-product-2', 'Ibuprofen 400mg', 'medication', 50, 'tablet', 50, 'IBU400', NOW(), NOW()),
('test-product-3', 'Low Stock Medication', 'medication', 100, 'tablet', 5, 'LOWSTOCK', NOW(), NOW());

INSERT INTO "Category" (id, name, description, code, created_at, updated_at) VALUES
('test-category-1', 'Pain Relief', 'Medications for pain relief', 'PAIN', NOW(), NOW()),
('test-category-2', 'Antibiotics', 'Antibiotic medications', 'ANTI', NOW(), NOW());
